name: notepad-plus-plus
title: Notepad++ (WINE)
summary: notepad-plus-plus is a free source code editor.
description: |
 Based on the powerful editing component Scintilla, notepad-plus-plus is written in C++ and uses pure Win32 API and STL which ensures a higher execution speed and smaller program size. By optimizing as many routines as possible without losing user friendliness, notepad-plus-plus is trying to reduce the world carbon dioxide emissions. When using less CPU power, the PC can throttle down and reduce power consumption, resulting in a greener environment.
adopt-info: notepad-plus-plus

confinement: strict
grade: stable
architectures:
  - build-on: amd64
  - build-on: i386
base: core20
compression: lzo

plugs:
  wine-runtime-c20:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime-core20
  wine-7-devel:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-7-devel-core20

environment:
  WINEDLLOVERRIDES: "mscoree,mshtml=" # Prevent pop-ups about Wine Mono and Wine Gecko
  RUN_EXE: "$SNAP_USER_DATA/notepad-plus-plus/notepad-plus-plus.exe"
  SOMMELIER_KEEP_CWD: "1" # Don't change the working directory so relative paths still work
  NO_AT_BRIDGE: "1" # Fix yad error Failed to connect to socket /tmp/dbus-xxx: No such file or directory
  DISABLE_WAYLAND: "1" # Fix gtk decoration under wayland session
  SYSTEM_WGETRC: $SNAP/wine-runtime/etc/wgetrc

apps:
  notepad-plus-plus:
    extensions: [ gnome-3-38 ]
    command: bin/sommelier run-exe
    plugs:
      - opengl
      - home
      - network
      - hardware-observe
      - process-control
      - cups-control
      - removable-media
    desktop: usr/share/applications/notepad-plus-plus.desktop
  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    extensions: [ gnome-3-38 ]
    command: bin/sommelier
    plugs:
      - home
      - network
      - hardware-observe
      - process-control
      - cups-control
      - removable-media
  # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    extensions: [ gnome-3-38 ]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  notepad-plus-plus:
    plugin: nil
    source: ./snap/local/src
    override-build: |
      snapcraftctl build
      set -ex
      ver=$(wget https://api.github.com/repos/notepad-plus-plus/notepad-plus-plus/releases -qO - 2>&1 | grep "Notepad++ " | sed s'|"| |g' | awk '{print $5}' | head -n1)
      snapcraftctl set-version "$ver"
      ./dl_npp
    stage:
      - bin
      - usr
      - wine-platform
      - wine-runtime
      - winedata
      - sommelier
    build-packages: [wget]
  # The sommelier script helps you snap Windows applications using Wine. It
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/mmtrt/sommelier-core.git
    source-branch: "tmp-core20"

  # This reverts changes from https://github.com/snapcore/snapcraft/pull/3586
  fix-fontconfig:
    plugin: nil
    after: [gnome-3-38-extension]
    override-prime: |
      sed -i '/snap-package/,+1d' $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch

  fix-bindtext:
    plugin: nil
    after: [gnome-3-38-extension]
    override-prime: |
      sed -i "$(grep -in bindtext $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch | cut -d':' -f1 | tail -2 | head -1)d" $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch
      sed -i "$(grep -in bindtext $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch | cut -d':' -f1 | tail -1)d" $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch
